Repository AY2223S1-CS2103-F09-2/tp, pull requests merged in 2022-10, with the labels that each got.

#52 Merge branch-EditGender-Qiaoran with master
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/GenderType.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#53 Merge branch-Sort with Master
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/GenderType.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/SortField.java
  src/main/java/seedu/address/model/person/SortFieldType.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/person/SortFieldTest.java
Labels: priority.High

#57 Merge Branch-deleteEvent-Vinod with Master
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High

#55 Merge Branch-DOB with Master
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/DateOfBirth.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#62 Merge Branch-DOB with master (PR review changes)
  build.gradle
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/DateOfBirth.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: priority.High

#64 Merge branch-EditGender-Qiaoran with Master (UserGuide and format issues)
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/Person.java
Labels: priority.High

#83 Merge branch-Sort with Master
  src/main/java/seedu/address/model/person/DateOfBirth.java
  src/main/java/seedu/address/model/person/SortField.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High

#74 Branch improve event date and time v1.3
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/StartDate.java
  src/main/java/seedu/address/model/event/StartTime.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/ui/EventCard.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
Labels: type.Enhancement, priority.High

#75 Merge branch-UpdateSettings with Master
  build.gradle
  docs/_config.yml
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task

#100 Merge branch-Sort (Developer Guide) with Master
  docs/DeveloperGuide.md
  docs/diagrams/SortFieldClassDiagram.puml
  docs/diagrams/SortPersonsSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/SortFieldClassDiagram.png
  docs/images/SortPersonsSequenceDiagram.png
Labels: type.Documentation, priority.High

#94 Merge branch-RenameDelete-Qiaoran with Master
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeletePersonCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java
Labels: priority.High

#101 Merge Branch-CompulsoryDOB-Hong Liang with master
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/DateOfBirth.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#103 Merge branch-DeveloperGuide-Qiaoran with Master
  docs/DeveloperGuide.md
  docs/diagrams/AddPersonActivityDiagram.xml
  docs/diagrams/AddPersonSequenceDiagram.xml
  docs/diagrams/EditPersonActivityDiagram.xml
  docs/diagrams/EditPersonSequenceDiagram.xml
  docs/images/AddPersonActivityDiagram.png
  docs/images/AddPersonSequenceDiagram.png
  docs/images/EditPersonActivityDiagram.png
  docs/images/EditPersonSequenceDiagram.png
Labels: type.Documentation, priority.High

#104 Add listEvents feature into DG
  docs/DeveloperGuide.md
  docs/diagrams/ListEventsSequenceDiagram.puml
  docs/images/ListEventsSequenceDiagram.png
Labels: type.Documentation

#108 Merge Branch-DGEvents-Vinod with master
  docs/DeveloperGuide.md
  docs/diagrams/AddEventSequenceDiagram.puml
  docs/diagrams/DeleteEventSequenceDiagram.puml
  docs/images/AddEventSequenceDiagram.png
  docs/images/DeleteEventSequenceDiagram.png
Labels: type.Documentation

#110 Merge Branch-DG-DOB Hong Liang with Master
  docs/DeveloperGuide.md
  docs/images/AddPersonActivityDiagram_DOB.png
  docs/images/EditPersonActivityDiagram_DOB.png
Labels: priority.High

#111 Merge branch-DeveloperGuidePuml-Qiaoran with Master
  docs/diagrams/AddPersonActivityDiagram.puml
  docs/diagrams/AddPersonActivityDiagram.xml
  docs/diagrams/AddPersonSequenceDiagram.puml
  docs/diagrams/AddPersonSequenceDiagram.xml
  docs/diagrams/EditPersonActivityDiagram.puml
  docs/diagrams/EditPersonActivityDiagram.xml
  docs/diagrams/EditPersonSequenceDiagram.puml
  docs/diagrams/EditPersonSequenceDiagram.xml
  docs/images/AddPersonActivityDiagram.png
  docs/images/AddPersonSequenceDiagram.png
  docs/images/EditPersonActivityDiagram.png
  docs/images/EditPersonSequenceDiagram.png
Labels: type.Documentation, priority.High

#93 Merge branch-TagEvent-Qiaoran with Master
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/TagEventCommand.java
  src/main/java/seedu/address/logic/commands/UntagEventCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TagEventCommandParser.java
  src/main/java/seedu/address/logic/parser/UntagEventCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UidList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Uid.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedUid.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/resources/view/EventListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, Double Reviews Needed

#102 Merge Branch-RefactorAddCommand-Hong Liang with Master
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#98 Merge branch-ChangeGender-Qiaoran with Master
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/GenderType.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#99 Merge Branch-editEventComand-Vinod with master
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/event/exceptions/DuplicateEventException.java
  src/main/java/seedu/address/model/event/exceptions/EventNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
Labels: type.Story, priority.High

#113 Merge branch-SortEvents with Master
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListEventsCommand.java
  src/main/java/seedu/address/logic/commands/ListPersonsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/ListEventsCommandParser.java
  src/main/java/seedu/address/logic/parser/ListPersonsCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/EventSortField.java
  src/main/java/seedu/address/model/event/EventSortFieldType.java
  src/main/java/seedu/address/model/event/StartDate.java
  src/main/java/seedu/address/model/event/StartTime.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/person/PersonSortField.java
  src/main/java/seedu/address/model/person/PersonSortFieldType.java
  src/main/java/seedu/address/model/person/SortFieldType.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/resources/view/StatsWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/ListPersonsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/SortFieldTest.java
Labels: priority.High, Double Reviews Needed

#134 Merge Branch-DOB-TestSuite Hong Liang with Master
  src/test/java/seedu/address/model/person/DateOfBirthTest.java
Labels: priority.Low

#124 Merge Branch-eventTitle-Vinod with Master
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventSortField.java
  src/main/java/seedu/address/model/event/EventTitle.java
  src/main/java/seedu/address/model/event/Purpose.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/ui/EventCard.java
Labels: priority.High, type.Task

#125 Merge branch-RefactorEditToEditPerson-Vinod with Master
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High, type.Task

#123 Merge branch-GenderTestSuite-Qiaoran with Master
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/GenderTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.Low

#122 Merge branch-MailingList-Qiaoran with Master
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/MailEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MailEventCommandParser.java
  src/main/java/seedu/address/model/event/UidList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High

#129 Merge branch-ImproveEventDateAndTime-V1.3
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/date/Date.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/person/DateOfBirth.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/model/date/DateTest.java
  src/test/java/seedu/address/model/person/DateOfBirthTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#132 Merge Branch-Statistics Hong Liang with Master
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/MakeStatsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MakeStatsCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/date/Date.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/statistics/StatisticData.java
  src/main/java/seedu/address/model/statistics/StatisticDataList.java
  src/main/java/seedu/address/model/statistics/exceptions/DuplicateDataException.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatsWindow.java
  src/main/resources/view/StatsWindow.fxml
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
Labels: type.Story, priority.High, Double Reviews Needed

#139 Merge branch-NewRemoveTags-V1.3 with Master
  src/main/java/seedu/address/commons/util/AppUtil.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonAdaptedUid.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#142 Merge Branch-Statistics (Bugfix) Hong Liang with Master
  src/main/resources/view/StatsWindow.fxml
Labels: type.Bug, priority.High, severity.High

#145 Merge branch-bugFix-Qiaoran with master
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
  src/main/java/seedu/address/model/person/Gender.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Bug, priority.High

#148 Merge branch-FixBugs-V1.3 with Master
  src/main/java/seedu/address/commons/util/AppUtil.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/MakeStatsCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/StatsWindow.java
  src/main/resources/view/StatsWindow.fxml
Labels: type.Bug

#136 Merge branch-UG-Marcus-V1.3 with Master
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/findEventsSportsCar.png
  docs/images/findPersonsAlexDavidResult.png
Labels: type.Documentation, priority.High

#140 Merge Branch-UG2 Hong Liang with Master
  docs/UserGuide.md
Labels: type.Documentation

#150 Merge branch-BugFix2-Qiaoran with master
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
Labels: type.Bug, priority.High

#152 Merge Branch-LandingPage Hong Liang with Master
  docs/images/Ui.png
  docs/index.md
Labels: type.Documentation, priority.High

#155 Merge Branch-LandingPage (minor fix) Hong Liang with Master
  docs/index.md
Labels: type.Documentation, priority.High

#199 Merge Branch-Rename-App Hong Liang with Master
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.Low

#200 Merge Branch-Fix-EditEvent-ErrorMessage Hong Liang with Master
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
Labels: type.Bug, severity.VeryLow
