Repository AY2223S1-CS2103-F09-2/tp, pull requests merged in 2022-11, with the labels that each got.

#202 Merge branch-UG-MailingList-Qiaoran with Master
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/TagEventCommand.java
  src/main/java/seedu/address/logic/commands/UntagEventCommand.java
Labels: type.Documentation, severity.Low

#203 Merge branch-TagEventBugFix-Qiaoran with Master
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/UidList.java
Labels: type.Bug, severity.Low

#208 Merge branch-BugFixSortOrder with Master
  docs/UserGuide.md
Labels: type.Bug, type.Documentation, priority.High, severity.Low

#207 Merge branch-BugFixWrongErrorMessageForNonPositiveIndex with Master
  docs/UserGuide.md
Labels: type.Bug, type.Documentation, priority.High, severity.Medium

#204 Merge Branch-UntagEvent-ErrorMessage Hong Liang with master
  src/main/java/seedu/address/logic/commands/UntagEventCommand.java
Labels: type.Bug, severity.VeryLow

#201 Merge Branch-Wrap-Texts Hong Liang with master
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug, severity.High

#206 Merge Branch-UG3 Hong Liang with master
  docs/UserGuide.md
Labels: type.Bug, severity.High

#221 Merge branch-PPP-Qiaoran with Master
  docs/team/qiaoran-m.md
Labels: type.Documentation, priority.High

#219 Merge branch-PPP-Benjamin with Master
  docs/team/benjamin-sim.md
Labels: type.Documentation, priority.High

#205 Merge branch-TimeFormatBugFix-Qiaoran with Master
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/StartTime.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
Labels: type.Bug, severity.Medium

#209 Merge branch-UpdateFindEventsPicture with Master
  docs/images/findEventsSportsCar.png
Labels: type.Documentation, severity.Medium

#212 Merge branch-FixFindPersons-UG
  docs/UserGuide.md
Labels: type.Bug, type.Documentation, severity.Medium

#210 Merge branch-FixEditPersonErrorMessage with Master
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/date/Date.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/date/DateTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, severity.Medium

#211 Merge branch-FixMakeStats-UG with Master
  docs/UserGuide.md
Labels: type.Bug, type.Documentation, severity.VeryLow

#213 Merge branch-DuplicatePersonsUG with Master
  docs/UserGuide.md
Labels: type.Documentation, severity.Medium

#224 Merge Branch-PPP2 Hong Liang into master
  docs/team/tanhl2000.md
Labels: type.Documentation, priority.High

#225 Merge branch-PPP2-Vinod with Master
  docs/team/vinodjayakumar124.md
Labels: type.Documentation, priority.High

#220 Merge branch-fixUG-Vinod with Master
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/model/event/Purpose.java
Labels: type.Bug, type.Documentation, priority.High

#217 Merge branch-DuplicateParameters-UG with Master
  docs/UserGuide.md
Labels: type.Documentation, severity.Medium

#215 Merge branch-PPP-Marcus with Master
  docs/DeveloperGuide.md
  docs/team/lfrostbytee.md
Labels: type.Documentation, priority.High

#222 Merge Branch-FutureDateCheck Hong Liang with master
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/date/Date.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: type.Bug, severity.Low

#226 Merge Branch-TypicalEvents-Vinod with Master
  src/main/java/seedu/address/model/event/Purpose.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: priority.High

#192 Merge branch-SortTesting with Master
  src/main/java/seedu/address/model/event/EventSortField.java
  src/main/java/seedu/address/model/person/PersonSortField.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListPersonsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ListPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonSortFieldTest.java
  src/test/java/seedu/address/model/person/SortFieldTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#231 Merge branch-EventAttributesTesting with Master
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/model/event/StartTime.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/FindEventsCommandTest.java
  src/test/java/seedu/address/logic/commands/ListEventsCommandTest.java
  src/test/java/seedu/address/logic/commands/ListPersonsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/date/DateTest.java
  src/test/java/seedu/address/model/event/StartTimeTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High, type.Task

#247 Merge branch-BugFixRemoveLines with Master
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: priority.High

#248 Merge branch-UG-V1.4 with Master
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#233 Merge Branch-EventTest-Vinod with Master
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/test/java/seedu/address/logic/commands/AddEventCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditEventCommandTest.java
  src/test/java/seedu/address/logic/commands/EditEventDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/event/EventTitleTest.java
  src/test/java/seedu/address/model/event/PurposeTest.java
  src/test/java/seedu/address/testutil/EditEventDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: priority.High, type.Task

#253 Merge Branch-LandingPage2 Hong Liang with master
  docs/images/Ui.png
Labels: type.Documentation, priority.High

#251 Merge Branch-AboutUs2 Hong Liang with master
  docs/AboutUs.md
Labels: type.Documentation, priority.High

#234 merge Branch-MakeStats-TestSuite Hong Liang with master
  src/main/java/seedu/address/logic/commands/MakeStatsCommand.java
  src/main/java/seedu/address/logic/parser/MakeStatsCommandParser.java
  src/main/java/seedu/address/model/statistics/StatisticData.java
  src/main/java/seedu/address/model/statistics/StatisticDataList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/MakeStatsCommandTest.java
  src/test/java/seedu/address/logic/parser/MakeStatsCommandParserTest.java
  src/test/java/seedu/address/model/statistics/StatisticsDataListTest.java
  src/test/java/seedu/address/model/statistics/StatisticsDataTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/TypicalAddressBook.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High, type.Task, Double Reviews Needed

#255 Merge branch-UpdateDG with Master
  docs/DeveloperGuide.md
  docs/diagrams/PersonSortFieldClassDiagram.puml
  docs/diagrams/SortPersonsSequenceDiagram.puml
  docs/images/PersonSortFieldClassDiagram.png
  docs/images/SortFieldClassDiagram.png
  docs/images/SortPersonsSequenceDiagram.png
Labels: type.Documentation, priority.High

#256 Merge branch-UpdateUG with Master
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#249 Merge branch-UG-V1.4 with Master
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#246 Merge Branch-v1.4BugFix-Qiaoran with Master
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High

#245 Merge Branch-MailingList-BugFix Hong Liang with master
  src/main/java/seedu/address/logic/commands/MailEventCommand.java
Labels: type.Bug, priority.High

#232 Merge Branch-DOB-TestSuite Hong Liang with master
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/date/DateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.High, type.Task, Double Reviews Needed

#258 Merge branch-UG-V1.4 with Master
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#257 Merge branch-DG-UserStory-Vinod with Master
  docs/DeveloperGuide.md
Labels: priority.High

#261 Merge Branch-updatePPP-Vinod with Master
  docs/team/vinodjayakumar124.md
Labels: type.Documentation

#266 Merge branch-UpdateUG-Vinod with Master
  docs/UserGuide.md
Labels: type.Documentation

#259 Merge branch-README-V1.4 with Master
  README.md
Labels: type.Documentation, priority.High

#254 Merge Branch-DG Hong Liang with master
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/AddPersonDobActivityDiagram.puml
  docs/diagrams/AddPersonGenderActivityDiagram.puml
  docs/diagrams/AddPersonSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeletePersonSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EditEventSequenceDiagram.puml
  docs/diagrams/EditPersonDobActivityDiagram.puml
  docs/diagrams/EditPersonGenderActivityDiagram.puml
  docs/diagrams/EditPersonSequenceDiagram.puml
  docs/diagrams/ListEventsSequenceDiagram.puml
  docs/diagrams/MailEventSequenceDiagram.puml
  docs/diagrams/MakeStatsSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/PersonAndEventClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/TagEventSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UntagEventSequenceDiagram.puml
  docs/images/AddEventSequenceDiagram.png
  docs/images/AddPersonActivityDiagram_DOB.png
  docs/images/AddPersonDobActivityDiagram.png
  docs/images/AddPersonGenderActivityDiagram.png
  docs/images/AddPersonSequenceDiagram.png
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/ComponentManagers.png
  docs/images/DeleteEventSequenceDiagram.png
  docs/images/DeletePersonSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/EditEventSequenceDiagram.png
  docs/images/EditPersonActivityDiagram_DOB.png
  docs/images/EditPersonDobActivityDiagram.png
  docs/images/EditPersonGenderActivityDiagram.png
  docs/images/EditPersonSequenceDiagram.png
  docs/images/ListEventsSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/MailEventSequenceDiagram.png
  docs/images/MakeStatsSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/PersonAndEventClassDiagram.png
  docs/images/PersonSortFieldClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/TagEventSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UndoSequenceDiagram.png
  docs/images/UntagEventSequenceDiagram.png
  docs/team/tanhl2000.md
Labels: type.Documentation, priority.High

#264 Merge branch-DG-ManualTestingAndEffort with Master
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High
